version: 2
jobs:
  build:
    docker:
       - image: containersai/website-builder:2018-12-12

    working_directory: ~/site

    steps:
      - checkout

      - run:
          name: Generating Site
          command: scripts/gen_site.sh "" -no_minify

      - run:
          name: Running Linters
          command: scripts/lint_site.sh